config/routes.rb
Rails.application.routes.draw do

  root "pages#home"

  resources :user_sessions
  resources :users

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]

  resources :freeagent_accounts
  resources :stripe_accounts
  resources :imports

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

end

app/views/pages/home.html.haml
%h1{style: "text-align:center"} Stripe to FreeAgent
%p.lead{style: "text-align:center"} An app that adds your Stripe charges, fees &amp; transfers to FreeAgent

%hr

- if current_user
  %p.lead{style: "text-align:center"} Hello #{current_user.email}
  %p{style: "text-align:center"}
    = link_to "Login with Stripe", "/auth/stripe_connect", class: "btn btn-success"
    = link_to "Login with FreeAgent", "/auth/freeagent", class: "btn btn-success"

  - if current_user.freeagent_accounts.count > 0 && current_user.stripe_accounts.count > 0
    %hr
    = form_for Import.new do |f|
      .row
        .form-group.col-md-6
          = f.label :stripe_account_id
          = f.select :stripe_account_id, current_user.stripe_accounts.map {|s| ["#{s.label} - #{s.stripe_user_id}", s.id]}, {}, {class: "form-control"}
        .form-group.col-md-6
          = f.label :freeagent_account_id
          = f.select :freeagent_account_id, current_user.freeagent_accounts.map {|f| [f.email, f.id]}, {}, {class: "form-control"}

        .text-center
          = f.submit "Run Import", class: "btn btn-primary btn-lg", data: {disable_with: "Running Import..."}

  %hr

  %table.table
    %thead
      %tr
        %th{width: "50%"} Stripe
        %th FreeAgent
    %tbody
      %tr
        %td
          - if current_user.stripe_accounts.count > 0
            - current_user.stripe_accounts.each do |sa|
              %p= sa.label
              %p= sa.stripe_user_id
              %p Import from #{sa.import_from}
              %p= link_to "Edit", edit_stripe_account_path(sa)
          - else
            %p Click the "Login with Stripe" button above
        %td
          - if current_user.freeagent_accounts.count > 0
            - current_user.freeagent_accounts.each do |fa|
              %p= fa.email
              %p Main Account: #{fa.main}
              %p Stripe Account: #{fa.stripe}
              %p= link_to "Edit", edit_freeagent_account_path(fa)
          - else
            %p Click the "Login with FreeAgent" button above

- else
  %p{style: "text-align:center; margin-bottom: 20px"}
    = link_to "Sign In", login_path, class: "btn btn-primary btn-lg"
    = link_to "Sign Up", new_user_path, class: "btn btn-success btn-lg"