config/routes.rb
Rails.application.routes.draw do

  root "pages#home"

  resources :user_sessions
  resources :users

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]

  resources :freeagent_accounts
  resources :stripe_accounts
  resources :imports

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController

  skip_before_filter :require_login

  def new
    @user = User.new
  end

  def create
    if @user = login(params[:email], params[:password])
      redirect_back_or_to(:root, notice: 'Login successful')
    else
      flash.now[:alert] = 'Login failed'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to(:root, notice: 'Logged out!')
  end

end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/_form.html.haml
= form_tag user_sessions_path, method: :post do
  .form-group
    = label_tag :email
    = text_field_tag :email, nil, class: "form-control"
  .form-group
    = label_tag :password
    = password_field_tag :password, nil, class: "form-control"
  
  = submit_tag "Login", class: "btn btn-success"

app/views/user_sessions/create.html.haml
%h1 UserSessions#create
%p Find me in app/views/user_sessions/create.html.haml

app/views/user_sessions/destroy.html.haml
%h1 UserSessions#destroy
%p Find me in app/views/user_sessions/destroy.html.haml

app/views/user_sessions/new.html.haml
%h1 Login

= render "form"